#!/usr/bin/env node
/**
 * Build-time GitHub metadata fetcher.
 *
 * Reads the list of `user/repo` slugs declared in `src/data/works.config.ts`
 * and pulls name / description / language / stars / pushed_at / html_url for
 * each, writing the combined result to `src/data/github-repos.generated.ts`.
 *
 * Design notes
 * - Emits a `.ts` file (not `.json`) to avoid toggling `resolveJsonModule`.
 * - Idempotent + fault-tolerant: if the API call fails (rate limit, offline,
 *   typo in repo name, ...) the previously-generated entries are preserved
 *   so a local build never loses data.
 * - Set `GITHUB_TOKEN` env-var to lift the 60/hr anonymous rate limit to
 *   5000/hr. Optional — not required for public repos.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const ROOT = resolve(__dirname, '..')

const CONFIG_PATH = resolve(ROOT, 'src/data/works.config.ts')
const OUTPUT_PATH = resolve(ROOT, 'src/data/github-repos.generated.ts')

/**
 * Tiny inline .env loader — supports `KEY=value`, `KEY="value"`, `KEY='value'`
 * and `#` comment lines. Exists to avoid adding `dotenv` as a build-time dep.
 * Does NOT overwrite existing `process.env` values so shell exports win.
 */
function loadDotEnv(path) {
  if (!existsSync(path)) return
  const text = readFileSync(path, 'utf8')
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const match = line.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/i)
    if (!match) continue
    const [, key, raw] = match
    const value = raw.replace(/^['"]|['"]$/g, '')
    if (process.env[key] === undefined) {
      process.env[key] = value
    }
  }
}

// `.env.local` is the canonical gitignored file for secrets (matches Vite).
// `.env` is also loaded as a fallback for CI / Vercel-style setups.
loadDotEnv(resolve(ROOT, '.env.local'))
loadDotEnv(resolve(ROOT, '.env'))

const TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || ''

/**
 * Pull the `github: 'user/repo'` values out of works.config.ts via a
 * forgiving regex — no need to evaluate TS at build time.
 */
async function extractRepoList() {
  const src = await readFile(CONFIG_PATH, 'utf8')
  const re = /github:\s*['"]([\w.-]+\/[\w.-]+)['"]/g
  const repos = new Set()
  let match
  while ((match = re.exec(src))) {
    repos.add(match[1])
  }
  return [...repos]
}

async function fetchRepo(slug) {
  const url = `https://api.github.com/repos/${slug}`
  const res = await fetch(url, {
    headers: {
      Accept: 'application/vnd.github+json',
      'User-Agent': 'velorah-site-build',
      ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
    },
  })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`HTTP ${res.status} ${res.statusText} ${body.slice(0, 120)}`)
  }
  const data = await res.json()
  return {
    slug,
    fullName: data.full_name,
    description: data.description || '',
    language: data.language || null,
    stars: data.stargazers_count ?? 0,
    forks: data.forks_count ?? 0,
    updatedAt: data.pushed_at || data.updated_at || '',
    htmlUrl: data.html_url,
    homepage: data.homepage || '',
    topics: Array.isArray(data.topics) ? data.topics : [],
  }
}

/**
 * Parse the previously-generated TS file to preserve entries when a fetch
 * fails. We only need the `export const githubRepos = {...}` object literal,
 * so a simple regex + JSON.parse is enough (the emitter below never writes
 * any TS-only syntax inside the object).
 */
async function readPrevious() {
  if (!existsSync(OUTPUT_PATH)) return {}
  try {
    const src = await readFile(OUTPUT_PATH, 'utf8')
    const match = src.match(/export const githubRepos\s*=\s*({[\s\S]*?})\s*as const/)
    if (!match) return {}
    return JSON.parse(match[1])
  } catch {
    return {}
  }
}

function emit(data) {
  return [
    '// AUTO-GENERATED by scripts/fetch-github.mjs — do not edit by hand.',
    '// Run `npm run fetch:github` (or `npm run build`) to refresh.',
    '',
    'export const githubRepos = ' + JSON.stringify(data, null, 2) + ' as const',
    '',
    'export type GithubRepoMeta = (typeof githubRepos)[keyof Omit<',
    '  typeof githubRepos,',
    '  "__fetchedAt"',
    '>]',
    '',
  ].join('\n')
}

async function main() {
  const repos = await extractRepoList()
  if (repos.length === 0) {
    console.log('[fetch-github] no `github: user/repo` entries found — skipping.')
    return
  }
  console.log(`[fetch-github] ${repos.length} repos: ${repos.join(', ')}`)
  if (TOKEN) {
    const preview = `${TOKEN.slice(0, 4)}\u2026${TOKEN.slice(-4)}`
    console.log(`[fetch-github] using GITHUB_TOKEN (${preview}) — 5000/hr, can read private repos.`)
  } else {
    console.log('[fetch-github] no GITHUB_TOKEN set — anonymous 60/hr limit, public repos only.')
    console.log('               drop one into .env.local as GITHUB_TOKEN=ghp_xxx to unlock private repos.')
  }

  const previous = await readPrevious()
  const next = { ...previous }

  for (const slug of repos) {
    try {
      const meta = await fetchRepo(slug)
      next[slug] = meta
      console.log(
        `  \u2713 ${slug}  lang=${meta.language ?? '\u2014'}  \u2605${meta.stars}  updated=${meta.updatedAt.slice(0, 10)}`,
      )
    } catch (err) {
      console.warn(`  \u2717 ${slug}  ${err.message}`)
      if (next[slug]) {
        console.warn(`    (kept previously cached value)`)
      }
    }
  }

  next.__fetchedAt = new Date().toISOString()

  await mkdir(dirname(OUTPUT_PATH), { recursive: true })
  await writeFile(OUTPUT_PATH, emit(next))
  console.log(`[fetch-github] wrote ${OUTPUT_PATH.replace(ROOT, '.')}`)
}

main().catch((err) => {
  console.error('[fetch-github] FAILED:', err)
  process.exit(0)
})
