// AUTO-GENERATED by scripts/fetch-github.mjs — do not edit by hand.
// Run `npm run fetch:github` (or `npm run build`) to refresh.

export const githubRepos = {
  "__fetchedAt": "2026-04-24T07:23:12.843Z",
  "xwenr/promptory": {
    "slug": "xwenr/promptory",
    "fullName": "xwenr/promptory",
    "description": "",
    "language": "TypeScript",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-04-23T09:07:01Z",
    "htmlUrl": "https://github.com/xwenr/promptory",
    "homepage": "",
    "topics": []
  },
  "xwenr/Fruit-Tea-Liquor": {
    "slug": "xwenr/Fruit-Tea-Liquor",
    "fullName": "xwenr/Fruit-Tea-Liquor",
    "description": "",
    "language": "JavaScript",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-04-17T12:00:28Z",
    "htmlUrl": "https://github.com/xwenr/Fruit-Tea-Liquor",
    "homepage": "",
    "topics": []
  },
  "xwenr/resumeflow": {
    "slug": "xwenr/resumeflow",
    "fullName": "xwenr/resumeflow",
    "description": "",
    "language": "JavaScript",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-04-14T05:30:31Z",
    "htmlUrl": "https://github.com/xwenr/resumeflow",
    "homepage": "https://resumeflow-puce.vercel.app",
    "topics": []
  },
  "xwenr/travel-plan": {
    "slug": "xwenr/travel-plan",
    "fullName": "xwenr/travel-plan",
    "description": "",
    "language": "Vue",
    "stars": 0,
    "forks": 0,
    "updatedAt": "2026-04-10T06:59:15Z",
    "htmlUrl": "https://github.com/xwenr/travel-plan",
    "homepage": "",
    "topics": []
  }
} as const

export type GithubRepoMeta = (typeof githubRepos)[keyof Omit<
  typeof githubRepos,
  "__fetchedAt"
>]
